# Configuration MySQL pour univ_scheduler (avec utilisateur root)
mysql.url=jdbc:mysql://localhost:3306/univ_scheduler?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
mysql.utilisateur=root
mysql.motdepasse=778512692
mysql.driver=com.mysql.cj.jdbc.Driver